version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/confessly
      - JWT_SECRET=change-me
      - SESSION_SECRET=change-me
      - ADMIN_TOKEN=admin-secret
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:4000
    depends_on:
      - backend
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
